# Generated by Django 2.1 on 2018-08-26 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=300)),
                ('cycle_day', models.CharField(max_length=200)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hydration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluid_name', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('additive_name', models.CharField(max_length=100)),
                ('additive_dose', models.CharField(max_length=100)),
                ('rate_duration', models.CharField(max_length=100)),
                ('administration_time', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('cycle', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('cycle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('diluent', models.CharField(max_length=100)),
                ('admin_route', models.CharField(max_length=100)),
                ('rate_duration', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('cycle', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('admin_route', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('diluent', models.CharField(max_length=100)),
                ('rate_duration', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('cycle', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrnMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('prn_indication', models.CharField(max_length=100)),
                ('admin_route', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100)),
                ('diluent', models.CharField(max_length=100)),
                ('rate_duration', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('cycle', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('division', models.CharField(max_length=200)),
                ('request', models.CharField(max_length=100, verbose_name='Requested By')),
                ('keyword', models.CharField(max_length=200)),
                ('disease_state', models.CharField(max_length=200)),
                ('number_of_cycles', models.IntegerField()),
                ('duration_of_cycles', models.IntegerField()),
                ('date_request', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6)),
                ('citation', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='prnmed',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prnmeds', to='tplan.Protocol'),
        ),
        migrations.AddField(
            model_name='premed',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premeds', to='tplan.Protocol'),
        ),
        migrations.AddField(
            model_name='med',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meds', to='tplan.Protocol'),
        ),
        migrations.AddField(
            model_name='lab',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='tplan.Protocol'),
        ),
        migrations.AddField(
            model_name='hydration',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydrations', to='tplan.Protocol'),
        ),
        migrations.AddField(
            model_name='condition',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='tplan.Protocol'),
        ),
    ]
