# Generated by Django 2.1 on 2018-08-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('dose', models.CharField(max_length=100)),
                ('admin_route', models.CharField(max_length=100, verbose_name='Route')),
                ('frequency', models.CharField(max_length=100)),
                ('sig', models.CharField(max_length=500)),
                ('qty', models.CharField(max_length=50)),
                ('refills', models.CharField(max_length=50)),
                ('dispense_as_writtern', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('comments', models.TextField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homemeds', to='tplan.Protocol')),
            ],
        ),
    ]
